import { normalizedIncludes } from "@/lib/property/property-search";

/**
 * Municipios de Colombia para el auto relleno de "Ciudad de expedición".
 *
 * Los 1.104 municipios de los 32 departamentos, deduplicados por nombre
 * (hay nombres repetidos entre departamentos, ej. Armenia en Antioquia y
 * Quindío). Se agregan "Cartagena" y "Bogotá D.C." porque es como la gente
 * las escribe en la cédula, aunque el nombre oficial sea otro.
 *
 * Fuente: marcovega/colombia-json (dominio público, DANE).
 * Es una lista de SUGERENCIAS: los campos siguen aceptando texto libre.
 */
export const MUNICIPIOS_COLOMBIA: readonly string[] = [
  "Abejorral",
  "Abriaquí",
  "Acacías",
  "Acandí",
  "Acevedo",
  "Achí",
  "Agrado",
  "Agua de Dios",
  "Aguachica",
  "Aguada",
  "Aguadas",
  "Aguazul",
  "Agustín Codazzi",
  "Aipe",
  "Albania",
  "Albán",
  "Alcalá",
  "Aldana",
  "Alejandría",
  "Algarrobo",
  "Algeciras",
  "Almaguer",
  "Almeida",
  "Alpujarra",
  "Altamira",
  "Alto Baudó",
  "Altos del Rosario",
  "Alvarado",
  "Amagá",
  "Amalfi",
  "Ambalema",
  "Anapoima",
  "Ancuyá",
  "Andalucía",
  "Andes",
  "Angelópolis",
  "Angostura",
  "Anolaima",
  "Anorí",
  "Anserma",
  "Ansermanuevo",
  "Anzoátegui",
  "Anzá",
  "Apartadó",
  "Apulo",
  "Apía",
  "Aquitania",
  "Aracataca",
  "Aranzazu",
  "Aratoca",
  "Arauca",
  "Arauquita",
  "Arbeláez",
  "Arboleda",
  "Arboledas",
  "Arboletes",
  "Arcabuco",
  "Arenal",
  "Argelia",
  "Ariguaní",
  "Arjona",
  "Armenia",
  "Armero",
  "Arroyohondo",
  "Astrea",
  "Ataco",
  "Ayapel",
  "Bagadó",
  "Bahía Solano",
  "Bajo Baudó",
  "Balboa",
  "Baranoa",
  "Baraya",
  "Barbacoas",
  "Barbosa",
  "Barichara",
  "Barranca de Upía",
  "Barrancabermeja",
  "Barrancas",
  "Barranco de Loba",
  "Barranquilla",
  "Becerril",
  "Belalcázar",
  "Bello",
  "Belmira",
  "Beltrán",
  "Belén",
  "Belén de los Andaquíes",
  "Belén de Umbría",
  "Berbeo",
  "Betania",
  "Betulia",
  "Betéitiva",
  "Bituima",
  "Boavita",
  "Bochalema",
  "Bogotá",
  "Bogotá D.C.",
  "Bojacá",
  "Bojayá",
  "Bolívar",
  "Bosconia",
  "Boyacá",
  "Brazuelo de Papayal",
  "Briceño",
  "Bucaramanga",
  "Bucarasica",
  "Buenaventura",
  "Buenavista",
  "Buenos Aires",
  "Buesaco",
  "Buga",
  "Bugalagrande",
  "Buriticá",
  "Busbanzá",
  "Cabrera",
  "Cabuyaro",
  "Cachipay",
  "Caicedo",
  "Caicedonia",
  "Caimito",
  "Cajamarca",
  "Cajibío",
  "Cajicá",
  "Calamar",
  "Calarcá",
  "Caldas",
  "Caldono",
  "Cali",
  "California",
  "Calima",
  "Caloto",
  "Campamento",
  "Campo de la Cruz",
  "Campoalegre",
  "Campohermoso",
  "Canalete",
  "Candelaria",
  "Cantagallo",
  "Cantón de San Pablo",
  "Caparrapí",
  "Capitanejo",
  "Caracolí",
  "Caramanta",
  "Carcasí",
  "Carepa",
  "Carmen de Apicalá",
  "Carmen de Carupa",
  "Carolina del Príncipe",
  "Cartagena",
  "Cartagena de Indias",
  "Cartagena del Chairá",
  "Cartago",
  "Carurú",
  "Casabianca",
  "Castilla la Nueva",
  "Caucasia",
  "Cañasgordas",
  "Cepitá",
  "Cereté",
  "Cerinza",
  "Cerrito",
  "Cerro de San Antonio",
  "Chachagüí",
  "Chaguaní",
  "Chalán",
  "Chaparral",
  "Charalá",
  "Charta",
  "Chibolo",
  "Chigorodó",
  "Chima",
  "Chimichagua",
  "Chimá",
  "Chinavita",
  "Chinchiná",
  "Chinácota",
  "Chinú",
  "Chipaque",
  "Chipatá",
  "Chiquinquirá",
  "Chiriguaná",
  "Chiscas",
  "Chita",
  "Chitagá",
  "Chitaraque",
  "Chivatá",
  "Chivor",
  "Choachí",
  "Chocontá",
  "Chámeza",
  "Chía",
  "Chíquiza",
  "Cicuco",
  "Cimitarra",
  "Circasia",
  "Cisneros",
  "Ciudad Bolívar",
  "Ciénaga",
  "Ciénaga de Oro",
  "Ciénega",
  "Clemencia",
  "Cocorná",
  "Coello",
  "Cogua",
  "Colombia",
  "Colosó",
  "Colón",
  "Concepción",
  "Concordia",
  "Condoto",
  "Confines",
  "Consacá",
  "Contadero",
  "Contratación",
  "Convención",
  "Copacabana",
  "Coper",
  "Corinto",
  "Coromoro",
  "Corozal",
  "Corrales",
  "Cota",
  "Cotorra",
  "Covarachía",
  "Coveñas",
  "Coyaima",
  "Cravo Norte",
  "Cuaspud",
  "Cubarral",
  "Cubará",
  "Cucaita",
  "Cucunubá",
  "Cucutilla",
  "Cumaral",
  "Cumaribo",
  "Cumbal",
  "Cumbitara",
  "Cunday",
  "Curillo",
  "Curití",
  "Curumaní",
  "Cuítiva",
  "Cáceres",
  "Cáchira",
  "Cácota",
  "Cáqueza",
  "Cértegui",
  "Cómbita",
  "Córdoba",
  "Cúcuta",
  "Dabeiba",
  "Dagua",
  "Dibulla",
  "Distracción",
  "Dolores",
  "Donmatías",
  "Dosquebradas",
  "Duitama",
  "Duranía",
  "Ebéjico",
  "El Atrato",
  "El Bagre",
  "El Banco",
  "El Cairo",
  "El Calvario",
  "El Carmen",
  "El Carmen de Atrato",
  "El Carmen de Bolívar",
  "El Carmen de Chucurí",
  "El Carmen de Viboral",
  "El Carmen del Darién",
  "El Castillo",
  "El Cerrito",
  "El Charco",
  "El Cocuy",
  "El Colegio",
  "El Copey",
  "El Doncello",
  "El Dorado",
  "El Dovio",
  "El Espinal",
  "El Espino",
  "El Guacamayo",
  "El Guamo",
  "El Molino",
  "El Paso",
  "El Paujil",
  "El Peñol",
  "El Peñón",
  "El Pital",
  "El Piñón",
  "El Playón",
  "El Retiro",
  "El Retorno",
  "El Retén",
  "El Roble",
  "El Rosal",
  "El Rosario",
  "El Santuario",
  "El Socorro",
  "El Tablón",
  "El Tambo",
  "El Tarra",
  "El Zulia",
  "El Águila",
  "Elías",
  "Encino",
  "Enciso",
  "Entrerríos",
  "Envigado",
  "Facatativá",
  "Falán",
  "Filadelfia",
  "Filandia",
  "Firavitoba",
  "Flandes",
  "Florencia",
  "Floresta",
  "Florida",
  "Floridablanca",
  "Florián",
  "Fonseca",
  "Fortul",
  "Fosca",
  "Francisco Pizarro",
  "Fredonia",
  "Fresno",
  "Frontino",
  "Fuente de Oro",
  "Fundación",
  "Funes",
  "Funza",
  "Fusagasugá",
  "Fómeque",
  "Fúquene",
  "Gachalá",
  "Gachancipá",
  "Gachantivá",
  "Gachetá",
  "Galapa",
  "Galeras",
  "Galán",
  "Gama",
  "Gamarra",
  "Garagoa",
  "Garzón",
  "Gigante",
  "Ginebra",
  "Giraldo",
  "Girardot",
  "Girardota",
  "Girón",
  "González",
  "Gramalote",
  "Granada",
  "Guaca",
  "Guacamayas",
  "Guacarí",
  "Guachené",
  "Guachetá",
  "Guachucal",
  "Guadalupe",
  "Guaduas",
  "Guaitarilla",
  "Gualmatán",
  "Guamal",
  "Guamo",
  "Guapotá",
  "Guapí",
  "Guaranda",
  "Guarne",
  "Guasca",
  "Guatapé",
  "Guataquí",
  "Guatavita",
  "Guateque",
  "Guavatá",
  "Guayabal de Síquima",
  "Guayabetal",
  "Guayatá",
  "Gutiérrez",
  "Guática",
  "Gámbita",
  "Gámeza",
  "Génova",
  "Gómez Plata",
  "Güepsa",
  "Güicán",
  "Hacarí",
  "Hatillo de Loba",
  "Hato",
  "Hato Corozal",
  "Hatonuevo",
  "Heliconia",
  "Herrán",
  "Herveo",
  "Hispania",
  "Hobo",
  "Honda",
  "Ibagué",
  "Icononzo",
  "Iles",
  "Imués",
  "Inzá",
  "Inírida",
  "Ipiales",
  "Isnos",
  "Istmina",
  "Itagüí",
  "Ituango",
  "Iza",
  "Jambaló",
  "Jamundí",
  "Jardín",
  "Jenesano",
  "Jericó",
  "Jerusalén",
  "Jesús María",
  "Jordán",
  "Juan de Acosta",
  "Junín",
  "Juradó",
  "La Apartada",
  "La Argentina",
  "La Belleza",
  "La Calera",
  "La Capilla",
  "La Ceja",
  "La Celia",
  "La Cruz",
  "La Cumbre",
  "La Dorada",
  "La Esperanza",
  "La Estrella",
  "La Florida",
  "La Gloria (Cesar)",
  "La Jagua de Ibirico",
  "La Jagua del Pilar",
  "La Llanada",
  "La Macarena",
  "La Merced",
  "La Mesa",
  "La Montañita",
  "La Palma",
  "La Paz",
  "La Peña",
  "La Pintada",
  "La Plata",
  "La Playa de Belén",
  "La Primavera",
  "La Salina",
  "La Sierra",
  "La Tebaida",
  "La Tola",
  "La Unión",
  "La Uribe",
  "La Uvita",
  "La Vega",
  "La Victoria",
  "La Virginia",
  "Labateca",
  "Labranzagrande",
  "Landázuri",
  "Lebrija",
  "Leiva",
  "Lejanías",
  "Lenguazaque",
  "Leticia",
  "Liborina",
  "Linares",
  "Litoral de San Juan",
  "Lloró",
  "Lorica",
  "Los Andes",
  "Los Córdobas",
  "Los Palmitos",
  "Los Patios",
  "Los Santos",
  "Lourdes",
  "Luruaco",
  "Lérida",
  "Líbano",
  "López de Micay",
  "Macanal",
  "Macaravita",
  "Maceo",
  "Machetá",
  "Madrid",
  "Magangué",
  "Magüí Payán",
  "Mahates",
  "Maicao",
  "Majagual",
  "Malambo",
  "Mallama",
  "Manatí",
  "Manaure",
  "Manaure Balcón del Cesar",
  "Manizales",
  "Manta",
  "Manzanares",
  "Maní",
  "Mapiripán",
  "Margarita",
  "Marinilla",
  "Maripí",
  "Mariquita",
  "Marmato",
  "Marquetalia",
  "Marsella",
  "Marulanda",
  "María la Baja",
  "Matanza",
  "Medellín",
  "Medina",
  "Medio Atrato",
  "Medio Baudó",
  "Medio San Juan",
  "Melgar",
  "Mercaderes",
  "Mesetas",
  "Milán",
  "Miraflores",
  "Miranda",
  "Mistrató",
  "Mitú",
  "Mocoa",
  "Mogotes",
  "Molagavita",
  "Momil",
  "Mompós",
  "Mongua",
  "Monguí",
  "Moniquirá",
  "Montebello",
  "Montecristo",
  "Montelíbano",
  "Montenegro",
  "Monterrey",
  "Montería",
  "Morales",
  "Morelia",
  "Morroa",
  "Mosquera",
  "Motavita",
  "Moñitos",
  "Murillo",
  "Murindó",
  "Mutatá",
  "Mutiscua",
  "Muzo",
  "Málaga",
  "Nariño",
  "Natagaima",
  "Nechí",
  "Necoclí",
  "Neira",
  "Neiva",
  "Nemocón",
  "Nilo",
  "Nimaima",
  "Nobsa",
  "Nocaima",
  "Norcasia",
  "Norosí",
  "Nueva Granada",
  "Nuevo Colón",
  "Nunchía",
  "Nuquí",
  "Nátaga",
  "Nóvita",
  "Obando",
  "Ocamonte",
  "Ocaña",
  "Oiba",
  "Oicatá",
  "Olaya",
  "Olaya Herrera",
  "Onzaga",
  "Oporapa",
  "Orito",
  "Orocué",
  "Ortega",
  "Ospina",
  "Otanche",
  "Ovejas",
  "Pachavita",
  "Pacho",
  "Padilla",
  "Paicol",
  "Pailitas",
  "Paime",
  "Paipa",
  "Pajarito",
  "Palermo",
  "Palestina",
  "Palmar",
  "Palmar de Varela",
  "Palmas del Socorro",
  "Palmira",
  "Palocabildo",
  "Pamplona",
  "Pamplonita",
  "Pandi",
  "Panqueba",
  "Paratebueno",
  "Pasca",
  "Pasto",
  "Patía",
  "Pauna",
  "Paya",
  "Paz de Ariporo",
  "Paz del Río",
  "Pedraza",
  "Pelaya",
  "Pensilvania",
  "Peque",
  "Pereira",
  "Pesca",
  "Piamonte",
  "Piedecuesta",
  "Piedras",
  "Piendamó",
  "Pijao",
  "Pijiño del Carmen",
  "Pinchote",
  "Pinillos",
  "Piojó",
  "Pisba",
  "Pitalito",
  "Pivijay",
  "Planadas",
  "Planeta Rica",
  "Plato",
  "Policarpa",
  "Polonuevo",
  "Ponedera",
  "Popayán",
  "Pore",
  "Potosí",
  "Pradera",
  "Prado",
  "Providencia",
  "Providencia y Santa Catalina Islas",
  "Pueblo Bello",
  "Pueblo Nuevo",
  "Pueblo Rico",
  "Pueblo Viejo",
  "Pueblorrico",
  "Puente Nacional",
  "Puerres",
  "Puerto Asís",
  "Puerto Berrío",
  "Puerto Boyacá",
  "Puerto Caicedo",
  "Puerto Carreño",
  "Puerto Colombia",
  "Puerto Concordia",
  "Puerto Escondido",
  "Puerto Gaitán",
  "Puerto Guzmán",
  "Puerto Leguízamo",
  "Puerto Libertador",
  "Puerto Lleras",
  "Puerto López",
  "Puerto Nare",
  "Puerto Nariño",
  "Puerto Parra",
  "Puerto Rico",
  "Puerto Rondón",
  "Puerto Salgar",
  "Puerto Santander",
  "Puerto Tejada",
  "Puerto Triunfo",
  "Puerto Wilches",
  "Pulí",
  "Pupiales",
  "Puracé",
  "Purificación",
  "Purísima",
  "Pácora",
  "Páez",
  "Páramo",
  "Quebradanegra",
  "Quetame",
  "Quibdó",
  "Quimbaya",
  "Quinchía",
  "Quipile",
  "Quípama",
  "Ragonvalia",
  "Ramiriquí",
  "Recetor",
  "Regidor",
  "Remedios",
  "Remolino",
  "Repelón",
  "Restrepo",
  "Ricaurte",
  "Rioblanco",
  "Riofrío",
  "Riohacha",
  "Rionegro",
  "Riosucio",
  "Risaralda",
  "Rivera",
  "Roberto Payán",
  "Roldanillo",
  "Roncesvalles",
  "Rondón",
  "Rosas",
  "Rovira",
  "Ráquira",
  "Río de Oro",
  "Río Iró",
  "Río Quito",
  "Río Viejo",
  "Sabana de Torres",
  "Sabanagrande",
  "Sabanalarga",
  "Sabanas de San Ángel",
  "Sabaneta",
  "Saboyá",
  "Sahagún",
  "Saladoblanco",
  "Salamina",
  "Salazar de Las Palmas",
  "Saldaña",
  "Salento",
  "Salgar",
  "Samacá",
  "Samaniego",
  "Samaná",
  "Sampués",
  "San Agustín",
  "San Alberto",
  "San Andrés",
  "San Andrés de Cuerquia",
  "San Andrés de Sotavento",
  "San Antero",
  "San Antonio",
  "San Antonio de Palmito",
  "San Antonio del Tequendama",
  "San Benito",
  "San Benito Abad",
  "San Bernardo",
  "San Bernardo del Viento",
  "San Calixto",
  "San Carlos",
  "San Carlos de Guaroa",
  "San Cayetano",
  "San Cristóbal",
  "San Diego",
  "San Eduardo",
  "San Estanislao",
  "San Fernando",
  "San Francisco",
  "San Gil",
  "San Jacinto",
  "San Jacinto del Cauca",
  "San Jerónimo",
  "San Joaquín",
  "San José",
  "San José de Albán",
  "San José de la Montaña",
  "San José de Miranda",
  "San José de Pare",
  "San José de Uré",
  "San José del Fragua",
  "San José del Guaviare",
  "San José del Palmar",
  "San Juan de Arama",
  "San Juan de Betulia",
  "San Juan de Rioseco",
  "San Juan de Urabá",
  "San Juan del Cesar",
  "San Juan Nepomuceno",
  "San Juanito",
  "San Lorenzo",
  "San Luis",
  "San Luis de Gaceno",
  "San Luis de Palenque",
  "San Marcos",
  "San Martín",
  "San Martín de Loba",
  "San Mateo",
  "San Miguel",
  "San Miguel de Sema",
  "San Onofre",
  "San Pablo",
  "San Pablo de Borbur",
  "San Pedro",
  "San Pedro de Cartago",
  "San Pedro de los Milagros",
  "San Pedro de Urabá",
  "San Pelayo",
  "San Rafael",
  "San Roque",
  "San Sebastián",
  "San Sebastián de Buenavista",
  "San Vicente",
  "San Vicente de Chucurí",
  "San Vicente del Caguán",
  "San Zenón",
  "Sandoná",
  "Santa Ana",
  "Santa Bárbara",
  "Santa Bárbara de Pinto",
  "Santa Catalina",
  "Santa Fe de Antioquia",
  "Santa Helena del Opón",
  "Santa Isabel",
  "Santa Lucía",
  "Santa Marta",
  "Santa María",
  "Santa Rosa",
  "Santa Rosa de Cabal",
  "Santa Rosa de Osos",
  "Santa Rosa de Viterbo",
  "Santa Rosa del Sur",
  "Santa Rosalía",
  "Santa Sofía",
  "Santacruz",
  "Santana",
  "Santander de Quilichao",
  "Santiago",
  "Santo Domingo",
  "Santo Domingo de Silos",
  "Santo Tomás",
  "Santuario",
  "Sapuyes",
  "Saravena",
  "Sardinata",
  "Sasaima",
  "Sativanorte",
  "Sativasur",
  "Segovia",
  "Sesquilé",
  "Sevilla",
  "Siachoque",
  "Sibaté",
  "Sibundoy",
  "Silvania",
  "Silvia",
  "Simacota",
  "Simijaca",
  "Simití",
  "Sincelejo",
  "Sincé",
  "Sipí",
  "Sitionuevo",
  "Soacha",
  "Soatá",
  "Socha",
  "Socotá",
  "Sogamoso",
  "Solano",
  "Soledad",
  "Solita",
  "Somondoco",
  "Sonsón",
  "Sopetrán",
  "Soplaviento",
  "Sopó",
  "Sora",
  "Soracá",
  "Sotaquirá",
  "Sotará",
  "Suaita",
  "Suaza",
  "Subachoque",
  "Sucre",
  "Suesca",
  "Supatá",
  "Supía",
  "Suratá",
  "Susa",
  "Susacón",
  "Sutamarchán",
  "Sutatausa",
  "Sutatenza",
  "Suán",
  "Suárez",
  "Sácama",
  "Sáchica",
  "Tabio",
  "Tadó",
  "Talaigua Nuevo",
  "Tamalameque",
  "Tame",
  "Taminango",
  "Tangua",
  "Taraira",
  "Tarazá",
  "Tarqui",
  "Tarso",
  "Tasco",
  "Tauramena",
  "Tausa",
  "Tello",
  "Tena",
  "Tenerife",
  "Tenjo",
  "Tenza",
  "Teorama",
  "Teruel",
  "Tesalia",
  "Tibacuy",
  "Tibaná",
  "Tibasosa",
  "Tibirita",
  "Tibú",
  "Tierralta",
  "Timaná",
  "Timbiquí",
  "Timbío",
  "Tinjacá",
  "Tipacoque",
  "Tiquisio",
  "Titiribí",
  "Toca",
  "Tocaima",
  "Tocancipá",
  "Togüí",
  "Toledo",
  "Tolú",
  "Tolú Viejo",
  "Tona",
  "Topaipí",
  "Toribío",
  "Toro",
  "Tota",
  "Totoró",
  "Trinidad",
  "Trujillo",
  "Tubará",
  "Tuchín",
  "Tuluá",
  "Tumaco",
  "Tunja",
  "Tununguá",
  "Turbaco",
  "Turbaná",
  "Turbo",
  "Turmequé",
  "Tuta",
  "Tutazá",
  "Támara",
  "Támesis",
  "Tópaga",
  "Túquerres",
  "Ubalá",
  "Ubaque",
  "Ubaté",
  "Ulloa",
  "Une",
  "Unguía",
  "Unión Panamericana",
  "Uramita",
  "Uribia",
  "Urrao",
  "Urumita",
  "Usiacurí",
  "Valdivia",
  "Valencia",
  "Valle de San José",
  "Valle de San Juan",
  "Valle del Guamuez",
  "Valledupar",
  "Valparaíso",
  "Vegachí",
  "Venadillo",
  "Venecia",
  "Ventaquemada",
  "Vergara",
  "Versalles",
  "Vetas",
  "Vianí",
  "Victoria",
  "Vigía del Fuerte",
  "Vijes",
  "Villa Caro",
  "Villa de Leyva",
  "Villa del Rosario",
  "Villa Rica",
  "Villagarzón",
  "Villagómez",
  "Villahermosa",
  "Villamaría",
  "Villanueva",
  "Villapinzón",
  "Villarrica",
  "Villavicencio",
  "Villavieja",
  "Villeta",
  "Viotá",
  "Viracachá",
  "Vista Hermosa",
  "Viterbo",
  "Vélez",
  "Yacopí",
  "Yacuanquer",
  "Yaguará",
  "Yalí",
  "Yarumal",
  "Yolombó",
  "Yondó",
  "Yopal",
  "Yotoco",
  "Yumbo",
  "Zambrano",
  "Zapatoca",
  "Zapayán",
  "Zaragoza",
  "Zarzal",
  "Zetaquira",
  "Zipacón",
  "Zipaquirá",
  "Zona Bananera",
  "Ábrego",
  "Íquira",
  "Úmbita",
  "Útica",
];

/** Filtra municipios sin importar tildes ni mayúsculas ("chia" → "Chía"). */
export function filterMunicipiosByQuery(
  query: string,
  limit = 14,
): string[] {
  const q = query.trim();
  if (!q) return [];
  const out: string[] = [];
  for (const name of MUNICIPIOS_COLOMBIA) {
    if (!normalizedIncludes(name, q)) continue;
    out.push(name);
    if (out.length >= limit) break;
  }
  return out;
}
